language: csharp
sudo: true
solution: sln/QuizChallenge.sln
before_install:
  - git submodule update --init --recursive
install:
  - nuget restore sln/QuizChallenge.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - sudo apt-get install gtk-sharp2
  - curl -sS https://api.nuget.org/packages/mono.cecil.0.9.5.4.nupkg > /tmp/mono.cecil.0.9.5.4.nupkg.zip
  - unzip /tmp/mono.cecil.0.9.5.4.nupkg.zip -d /tmp/cecil
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll .
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll /tmp/cecil/
  - git clone --depth=50 git://github.com/csMACnz/monocov.git ../../csMACnz/monocov
  - cd ../../csMACnz/monocov
  - cp /tmp/cecil/Mono.Cecil.dll .
  - ./configure
  - make
  - sudo make install
  - cd ../../robinkanters/quiz-challenge
script:
  - xbuild /p:Configuration=Release sln/QuizChallenge.sln
  - mono --debug --profile=monocov:outfile=monocovCoverage.cov,+QuizChallenge ./src/packages/NUnit.Console.3.0.0-beta-3/tools/nunit-console.exe --process=Single ./src/QuizChallenge.Model.Test/bin/Release/QuizChallenge.Model.Test.dll
  - export LD_LIBRARY_PATH=/usr/local/lib
  - monocov --export-xml=monocovCoverage monocovCoverage.cov
  - cat monocovCoverage.cov
