language: csharp
solution: sln/QuizChallenge.sln
mono:
  - latest
before_install:
  - git submodule update --init --recursive
install:
  - nuget restore sln/QuizChallenge.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release sln/QuizChallenge.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe --profile=monocov:outfile=monocovCoverage.cov,+QuizChallenge ./src/QuizChallenge.Model.Test/bin/Release/QuizChallenge.Model.Test.dll
